import EmailConfirmation from '@/components/emailConfirmation'
import Head from 'next/head'

export default function LoginrPage() {
    return <>
        <Head>
            <title>Email Confirmation</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <EmailConfirmation />
    </>

}