import Register from "@/components/register"
import Head from 'next/head'

export default function RegisterPage() {
    return <>
        <Head>
            <title>Register</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Register />
    </>

}