import Head from 'next/head'
import { Inter } from 'next/font/google'
import { useEffect, useState } from "react"
import Confetti from "react-confetti";
import 'react-toastify/dist/ReactToastify.css';
import useWindowSize from 'react-use/lib/useWindowSize'
import { Button } from '@mui/material';
import { useApi } from '@/components/api';
import { useRouter } from 'next/router';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [showConfetti, setShowConfetti] = useState<boolean>(false);
  const { width, height } = useWindowSize()
  const api = useApi()
  const router = useRouter()

  useEffect(() => {
    if (api.getToken()) {
      setShowConfetti(true)
    }
  }, [])

  setTimeout(() => {
    setShowConfetti(false);
  }, 6000);


  return (
    <>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {showConfetti && <Confetti numberOfPieces={200} width={width} height={height} />}

      <main className={`${inter.className}`}>
        Hello World
        <Button color="error" variant="contained" onClick={() => { api.logOut(); router.push("/login") }}>Exit</Button>
      </main>
    </>
  )
}
