import Workers from "@/components/workers";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Id perspiciatis
        excepturi recusandae corporis ipsum, necessitatibus similique aliquid
        ducimus et, esse nemo at explicabo quidem vel commodi culpa saepe!
        Atque, doloremque.

        <Workers />
      </main>
    </>
  );
}
